### ISSUE TITLE
All menu items have an empty "Overview"on Android

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/extension-workshop#253] opened 2019-07-26 14:07 UTC
### Describe the problem and steps to reproduce it:
1. Open the extension workshop on an Android device - https://extensionworkshop-dev.allizom.org/
2. Click on the hamburger menu
3. Select "Manage" from the available options
4. Click on the down arrow to expand the "Manage" menu
5. Observe the contents available in the Overview section

### What happened?
The Overview is empty

### What did you expect to happen?
The Overview should include the same contents that are available on Desktop

### Anything else we should know?
- the other documentation sections with an empty overview are:
  - Enterprise
  - Themes
  - Extension Basics
 
![2019-07-26_17-00-55](https://user-images.githubusercontent.com/31961530/61957330-b31ebe80-afc7-11e9-8c8b-b5bdb57e63ef.gif)

**Comment by caitmuenster** [comment] 2019-07-26 14:21
@atruong, do you know if this section has been checked in yet?

**Comment by andrewtruongmoz** [comment] 2019-07-26 16:29
Content needs to be transferred over for those sections; they're currently are unassigned.  

(fyi, the wrong person was tagged)

**Comment by caitmuenster** [comment] 2019-07-26 16:48
Thanks! :) Ok, it sounds like this should be taken care of once the content gets built out.

**Comment by caitmuenster** [comment] 2019-09-03 17:12
@AlexandraMoga The overview pages should all be built out now. :) If you have time this week, could you re-check this on Android and see if this issue is still valid?

**Comment by AlexandraMoga** [comment] 2019-09-06 08:31
@caitmuenster I had a closer look at all the menu options (Extension Basics, Documentation Topics with all its subsections, Community) and it looks like the Overview portion is still empty for all of them.

Here is a comparison for the Community menu: 

![image](https://user-images.githubusercontent.com/31961530/64412687-a39b9680-d098-11e9-9d98-58a1b8b3ef42.png)

The rest of the content has been indeed added, so this issue is strictly limited to the Overview portion.

**Comment by caitmuenster** [comment] 2019-09-13 16:52
Hm, I think this might be expected behavior. 

What do you think, @muffinresearch?

**Comment by muffinresearch** [comment] 2019-09-16 15:26
Does seem like a bug, I can't see a reason why that content should be withheld.

**Comment by caitmuenster** [comment] 2019-09-16 15:50
The dropdown should show other documents in that section.

**Comment by muffinresearch** [comment] 2019-09-25 12:31
Looks like this would duplicate content that's already shown in the page. I took at look at making the change but it requires quite a lot of changes to the nav because once the content is displayed it needs to close the nav on-click as well as scroll to the right position. 

As the same navigation content is in the page already, I don't know if this is enough of a problem to warrant that change and indeed it might be better keeping the dropdown menu simpler.

**Comment by caitmuenster** [comment] 2019-09-25 19:04
Thanks @muffinresearch! If the fix duplicates content and also requires a lot of changes to the nav, I think this is fine. Let's go ahead and close this issue.

**Closed by caitmuenster** 2019-09-25 19:04 UTC
Labels: priority: p2, question
