### ISSUE TITLE
Preserve double dashes in titles (for web-ext reference)

### ISSUE THREAD

**Issue by kumar303** [mozilla/extension-workshop#505] opened 2019-10-10 19:35 UTC
### Describe the problem and steps to reproduce it:

* Go to https://extensionworkshop.com/documentation/develop/web-ext-command-reference/
* Scroll to the first documented option, which is `--as-needed`

### What happened?

The double dash is rendered as em-dash (**–as-needed**).

### What did you expect to happen?

The double dash should be exactly that, like `--as-needed`. This is important because one will need to type the double dash in a terminal to use this option.

### Anything else we should know?

I'm pretty sure this was rendered as expected on MDN but I don't know how to view the old page to be sure.

**Comment by kumar303** [comment] 2019-10-10 19:43
Yeah, I double checked that the double dash (and not an em-dash) is in the source: `#### --as-needed`

https://raw.githubusercontent.com/mozilla/extension-workshop/4cde5f50ddcc90b38f17d922ee0318a38e6455f7/documentation/develop/web-ext-command-reference.md

**Comment by caitmuenster** [comment] 2019-10-10 19:57
Thanks @kumar303! The content for this page should be the same as https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/web-ext_command_reference$revision/1584566.

**Comment by caitmuenster** [comment] 2019-10-11 17:51
It looks like this is [caused by our renderer](https://github.com/jekyll/jekyll/issues/620). @muffinresearch, any chance you could look into a fix for this?

**Closed** 2019-10-14 21:46 UTC

**Comment by kumar303** [comment] 2019-10-23 19:04
Thanks!
