### ISSUE TITLE
The video player can't be dismissed with Esc key if the video is paused

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/extension-workshop#463] opened 2019-09-26 06:30 UTC
### Describe the problem and steps to reproduce it:

1. Open a page section that contains a video - see https://extensionworkshop-dev.allizom.org/documentation/publish/#promote-your-extension
2. Play the video present in this section
3. Pause the video
4. Press the Esc key to close the player

### What happened?
The video player is not closed

### What did you expect to happen?
The video player is closed

### Anything else we should know?
The player can't be closed either when you resume the video after having paused it

**Comment by muffinresearch** [comment] 2019-09-26 08:54
Thanks - this is a good catch, the problem is caused by the focus being on the video iframe when you've interacted with it.

**Comment by muffinresearch** [comment] 2019-09-26 10:23
Investigating this, there's simply no way to achieve this easily. Youtube doesn't provide keyboard events and when the iframe is focused there's no way to listen to keyboard events.

The only way we could possible fix it, is to use a completely new player that overlays the iframe and provides custom controls so that the iframe never gets focus. 

Note: https://www.mozilla.org/en-US/ also has the same issue with their video player.

**Comment by muffinresearch** [comment] 2019-09-30 10:31
I've filed an upstream bug in case they'll consider adding support for key events. https://issuetracker.google.com/issues/141825188

**Comment by muffinresearch** [comment] 2020-07-30 19:06
Doesn't look like this will ever be fixable, there's been no change on the upstream bug. They don't consider it important. Since there's nothing actionable I'm going to close it out.

**Closed by muffinresearch** 2020-07-30 19:06 UTC
Labels: Accessibility
