### ISSUE TITLE
Issue with refreshing the website

### ISSUE THREAD

**Issue by shashankcoc** [mozilla/extension-workshop#650] opened 2020-06-14 08:25 UTC
### Describe the problem and steps to reproduce it:
Steps are very simple:
1. Create for signup and subscribe for newsletter.
2.Click the checkbox and submit.
3.After that refresh the website.
4.The same email address comes back. 
5.Browser Mozilla Firefox 

### What happened?
Does'nt Refresh at all
### Anything else we should know?

Should refresh the website and open up a clear page.
![Bug_Refresh](https://user-images.githubusercontent.com/44526306/84588606-7f01f580-ae46-11ea-8c79-98e1d40710ee.jpg)

**Comment by muffinresearch** [comment] 2020-06-25 18:07
This sounds like a duplicate of https://github.com/mozilla/extension-workshop/issues/227

**Closed** 2020-06-25 18:07 UTC
