### ISSUE TITLE
Register/Login button should change it's state into something else

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/extension-workshop#138] opened 2019-03-27 09:03 UTC
Followup for https://github.com/mozilla/addons-server/issues/10909 and https://github.com/mozilla/addons-frontend/issues/7696

1. Load AMO dev or AMO stage and click on Extension Workshop
2. Login using the Register/Login
3. Return to EW page and observe the button's name

Expected result:
The "Register/Login" should be "Dev Hub".

Actual result:
The "Register/Login" is still displayed. It looks like the user should login again.

Notes:
Reproducible on both AMO dev and AMO stage - FF65(Win10 and Android 8.0). 

![already logged in](https://user-images.githubusercontent.com/33448286/55063048-db30fc00-507f-11e9-89fd-4a5f1160eb93.gif)

**Comment by muffinresearch** [comment] 2019-03-27 14:18
@ioanarusiczki this isn't fixable at the moment since the extension workshop has no concept of login state and there are no current plans to add that.

**Comment by caitmuenster** [comment] 2019-03-27 16:07
Thanks @muffinresearch! Yeah, the best thing to do here is to update the copy of the button to something like "Manage/Submit Extension."

**Comment by muffinresearch** [comment] 2019-03-28 12:10
@caitmuenster the changes had to be reverted as they caused a regression (see #146)

**Comment by caitmuenster** [comment] 2019-03-28 22:15
I took a closer look at this today, and I don't quite have the skills to fix the layout issues caused by changing the copy on the button. I'd accept contributions to this.

**Comment by muffinresearch** [comment] 2019-07-25 16:32
This is now Submit or Manage so I think we can close this out.

**Closed by muffinresearch** 2019-07-25 16:32 UTC
