### ISSUE TITLE
After clicking on a video the loading indicator doesn't spin

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/extension-workshop#137] opened 2019-03-27 13:57 UTC
Followup https://github.com/mozilla/addons-frontend/issues/7696 

STR:
1. Load AMO and click the EW link
2. Go to a video from the page -> Attract Users with Content and Design -> What’s Great Content and Design?
3. Click the video and observe the loading indicator

Expected results:
Until the video loads the indicator is spinning.

Actual result:
The indicator doesn't spin.

Notes: 
It is reproducible on AMO - FF65 (Win10 & Android 8.0).

This seems to be a browser issue because I could not reproduce it on Chrome.

with FF

![loading state on ff](https://user-images.githubusercontent.com/33448286/55081628-e2b8cb00-50a8-11e9-9305-c02bead28aef.gif)

with Chrome

![loading state on chrome](https://user-images.githubusercontent.com/33448286/55081655-ef3d2380-50a8-11e9-9064-69b8faa9e3c4.gif)

**Comment by ioanarusiczki** [comment] 2019-03-27 14:36
@willdurand Sorry, I had no idea it's a separate repo for EW. Thanks @muffinresearch for transfering all the filed issues here.

**Comment by muffinresearch** [comment] 2019-03-27 16:28
Possibly caused by CSP since this works locally.

**Comment by muffinresearch** [comment] 2019-03-29 13:25
This is a CSP issue, [animate elements in the SVG cause style-src violations](https://bugzilla.mozilla.org/show_bug.cgi?id=1459872). We'll need to workaround this by moving to a CSS-based animation instead.

**Comment by muffinresearch** [comment] 2019-08-16 17:55
You can now see the video in https://extensionworkshop-dev.allizom.org/documentation/publish/

**Closed** 2019-08-21 22:16 UTC
Labels: bug, priority: p3

**Comment by ioanarusiczki** [comment] 2019-08-22 09:00
@muffinresearch 
This is verified on EW dev with FF68(Win10). 

![spinner](https://user-images.githubusercontent.com/33448286/63498526-c17ccf00-c4ce-11e9-952c-4d8e7fd618da.gif)

I don't know if that's something expected or could be fixed from our side but I've noticed that on mobile platforms the video won't automatically start ( that's the desktop behavior). On mobile (Android or iOS) there's the Play red button (that's youtube's) which has to be tapped to start the video.  It has the same behavior on FF or Chrome. 

![videotogif_2019 08 22_11 37 49](https://user-images.githubusercontent.com/33448286/63501369-2686f380-c4d4-11e9-91b1-527bd67d7697.gif)
