### ISSUE TITLE
Telegram link not working(Connect With Us Section)

### ISSUE THREAD

**Issue by Patil2099** [mozilla/extension-workshop#274] opened 2019-08-02 16:29 UTC
### Describe the problem and steps to reproduce it:

![bugmozilla](https://user-images.githubusercontent.com/35653876/62384509-39ab4100-b570-11e9-9112-0721744d3125.jpg)

### What happened?
The link for the telegram group points to telegram.org

### What did you expect to happen?
It should point to the actual link for joining the telegram group

**Comment by championshuttler** [comment] 2019-08-03 17:18
Duplicate of #197. Should be closed :)

**Closed** 2019-08-03 17:40 UTC
